# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install node_modules
        run: npm install
      - name: build the project
        run: npm run build 
      - name: Sets the vercel env
        run: |
          cd .next
          mkdir .vercel
          cd .vercel
          touch project.json
          echo '{"projectId":"prj_dhwtU2DamMwvicwL5KupYsvJFsrz",
          "orgId":"tYh1JRsbx3ZIwVswy7KJFZXV"}' > project.json
      - name: Deploying the project
        run: npm run deploy    
      - name: Set up finish
        run: echo "hurray!!!"

